variable "project_id" {
  type        = string
  description = "Id for the Google Cloud project."
}

variable "region" {
  type        = string
  default     = "us-central1"
  description = "https://cloud.google.com/compute/docs/regions-zones"
}

variable "cluster_name" {
  type        = string
  default     = "gke-primary-cluster"
  description = "GKE primary cluster name (without nodes)."
}

variable "multicluster_mode" {
  type        = string
  default     = "connected"
  description = "Determines whether remote secrets should be autogenerated across fleet cluster."
}

variable "enable_cni" {
  type        = bool
  default     = true
  description = "Determines whether to enable CNI for this ASM installation. Required to use Managed Data Plane (MDP)."
}

variable "enable_mesh_feature" {
  type        = bool
  default     = true
  description = "Determines whether the module enables the mesh feature on the fleet."
}

variable "enable_fleet_registration" {
  type        = bool
  default     = true
  description = "Determines whether the module registers the cluster to the fleet."
}

variable "gke_endpoint" {
  description = "Endpoint of the GKE cluster."
}

variable "gke_ca_certificate" {
  description = "Encoded CA certificate of the GKE cluster."
}
